// <auto-generated />
namespace _497FinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserModelChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserModelChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201811261900263_UserModelChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
